# Importação das bibliotecas

In [138]:
import json
from pathlib import Path

import pandas as pd

# Configuração dos caminhos

In [139]:
RAW_DIR = Path("../collector/data/raw")
PROCESSED_DIR = Path("../collector/processed")

FILES = [
    "spirit.json",
    "mouz.json",
    "falcons.json",
    "fut.json",
    "vitality.json",
    "furia.json"
]

# Função para carregar JSON

In [140]:
def load_json(filepath):
    with open(filepath, "r", encoding="utf-8") as file:
        return json.load(file)

# Carregando os dados

In [141]:
all_matches = []

for filename in FILES:

    filepath = f"{RAW_DIR}/{filename}"

    matches = load_json(filepath)

    for match in matches:
        match["_source"] = filename
        all_matches.append(match)

matches_df = pd.json_normalize(all_matches)

matches_df = matches_df.rename(
    columns={
        "id": "match_id",

        "team1.id": "team1_id",
        "team1.name": "team1_name",
        "team1.score": "team1_score",
        "team1.rank": "team1_rank",

        "team2.id": "team2_id",
        "team2.name": "team2_name",
        "team2.score": "team2_score",
        "team2.rank": "team2_rank",

        "winner.id": "winner_id",
        "winner.name": "winner_name"
    }
)

# Criando o DataFrame

In [142]:
matches_df = pd.json_normalize(all_matches)

matches_df.head()

,id,maps,best_of,date,event,_source,team1.id,team1.name,team1.score,team1.rank,team2.id,team2.name,team2.score,team2.rank,winner.id,winner.name
0,2396949,"[{'id': 3, 'name': 'Ancient', 'team1_score': 1...",3,2026-09-05,BLAST Open Porto 2026,spirit.json,7020,Spirit,2,1,11283,Falcons,0,3,7020,Spirit
1,2396943,"[{'id': 11, 'name': 'Cache', 'team1_score': 13...",3,2026-08-31,BLAST Open Porto 2026,spirit.json,7020,Spirit,2,1,8297,FURIA,0,7,7020,Spirit
2,2396932,"[{'id': 4, 'name': 'Dust2', 'team1_score': 13,...",3,2026-08-28,BLAST Open Porto 2026,spirit.json,7020,Spirit,2,1,5995,G2,0,8,7020,Spirit
3,2396924,"[{'id': 3, 'name': 'Ancient', 'team1_score': 1...",3,2026-08-26,BLAST Open Porto 2026,spirit.json,7020,Spirit,2,1,13926,DENDELE,0,36,7020,Spirit
4,2396614,"[{'id': 11, 'name': 'Cache', 'team1_score': 10...",5,2026-08-23,Esports World Cup 2026,spirit.json,7020,Spirit,3,1,13286,FUT,1,5,7020,Spirit

# Inspecionando a estrutura

In [143]:
matches_df.shape
matches_df.columns
matches_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           120 non-null    int64
 1   maps         120 non-null    object
 2   best_of      120 non-null    int64
 3   date         120 non-null    str
 4   event        120 non-null    str
 5   _source      120 non-null    str
 6   team1.id     120 non-null    int64
 7   team1.name   120 non-null    str
 8   team1.score  120 non-null    int64
 9   team1.rank   120 non-null    int64
 10  team2.id     120 non-null    int64
 11  team2.name   120 non-null    str
 12  team2.score  120 non-null    int64
 13  team2.rank   120 non-null    int64
 14  winner.id    120 non-null    int64
 15  winner.name  120 non-null    str
dtypes: int64(9), object(1), str(6)
memory usage: 22.2+ KB

# Renomeando as colunas

In [144]:
matches_df = matches_df.rename(
    columns={
        "id": "match_id",

        "team1.id": "team1_id",
        "team1.name": "team1_name",
        "team1.score": "team1_score",
        "team1.rank": "team1_rank",

        "team2.id": "team2_id",
        "team2.name": "team2_name",
        "team2.score": "team2_score",
        "team2.rank": "team2_rank",

        "winner.id": "winner_id",
        "winner.name": "winner_name"
    }
)

matches_df.head()

,match_id,maps,best_of,date,event,_source,team1_id,team1_name,team1_score,team1_rank,team2_id,team2_name,team2_score,team2_rank,winner_id,winner_name
0,2396949,"[{'id': 3, 'name': 'Ancient', 'team1_score': 1...",3,2026-09-05,BLAST Open Porto 2026,spirit.json,7020,Spirit,2,1,11283,Falcons,0,3,7020,Spirit
1,2396943,"[{'id': 11, 'name': 'Cache', 'team1_score': 13...",3,2026-08-31,BLAST Open Porto 2026,spirit.json,7020,Spirit,2,1,8297,FURIA,0,7,7020,Spirit
2,2396932,"[{'id': 4, 'name': 'Dust2', 'team1_score': 13,...",3,2026-08-28,BLAST Open Porto 2026,spirit.json,7020,Spirit,2,1,5995,G2,0,8,7020,Spirit
3,2396924,"[{'id': 3, 'name': 'Ancient', 'team1_score': 1...",3,2026-08-26,BLAST Open Porto 2026,spirit.json,7020,Spirit,2,1,13926,DENDELE,0,36,7020,Spirit
4,2396614,"[{'id': 11, 'name': 'Cache', 'team1_score': 10...",5,2026-08-23,Esports World Cup 2026,spirit.json,7020,Spirit,3,1,13286,FUT,1,5,7020,Spirit

# Verificando valores ausentes

In [145]:
matches_df.isna().sum()

missing = matches_df.isna().sum()

missing[missing > 0]

Series([], dtype: int64)

# Tratando a coluna de data

In [146]:
matches_df["date"] = pd.to_datetime(
    matches_df["date"],
    errors="coerce"
)

matches_df["date"].dtype

dtype('<M8[us]')

# Tratando colunas numéricas

In [147]:
numeric_columns = [
    "match_id",
    "team1_id",
    "team2_id",
    "team1_score",
    "team2_score",
    "team1_rank",
    "team2_rank",
    "winner_id",
    "best_of"
]

for column in numeric_columns:

    matches_df[column] = pd.to_numeric(
        matches_df[column],
        errors="coerce"
    )

matches_df = matches_df.drop_duplicates(
    subset="match_id"
).reset_index(drop=True)

# Verificando IDs duplicados

In [148]:
print(
    f"Total de partidas: {len(matches_df)}"
)

print(
    f"IDs únicos: {matches_df['match_id'].nunique()}"
)

print(
    f"IDs duplicados: {matches_df['match_id'].duplicated().sum()}"
)

matches_df = matches_df.drop_duplicates(
    subset="match_id"
)

Total de partidas: 120
IDs únicos: 120
IDs duplicados: 0

# Criando resultado das equipes

In [149]:
def get_result(row, team_id):

    if row["winner_id"] == team_id:
        return "W"

    return "L"
# Resultado do Team 1
matches_df["team1_result"] = matches_df.apply(
    lambda row: get_result(
        row,
        row["team1_id"]
    ),
    axis=1
)
# Resultado do Team 2
matches_df["team2_result"] = matches_df.apply(
    lambda row: get_result(
        row,
        row["team2_id"]
    ),
    axis=1
)

# Verificando:

matches_df[
    [
        "team1_name",
        "team1_result",
        "team2_name",
        "team2_result"
    ]
].head()

  team1_name team1_result team2_name team2_result
0     Spirit            W    Falcons            L
1     Spirit            W      FURIA            L
2     Spirit            W         G2            L
3     Spirit            W    DENDELE            L
4     Spirit            W        FUT            L

# Criando diferença de rounds

In [150]:
matches_df["score_difference"] = (
    matches_df["team1_score"]
    - matches_df["team2_score"]
).abs()

# Criando o DataFrame de mapas

In [151]:
maps_data = []

for _, match in matches_df.iterrows():

    match_id = match["match_id"]

    for map_data in match["maps"]:

        maps_data.append({
            "match_id": match_id,
            "map_id": map_data["id"],
            "map_name": map_data["name"],
            "team1_map_score": map_data["team1_score"],
            "team2_map_score": map_data["team2_score"]
        })

# Criando diferença de rounds por mapa

In [152]:
maps_df["round_difference"] = (
    maps_df["team1_map_score"]
    - maps_df["team2_map_score"]
).abs()

# Verificando o DataFrame de partidas

In [153]:
matches_df.head()
matches_df.shape
matches_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   match_id          120 non-null    int64
 1   maps              120 non-null    object
 2   best_of           120 non-null    int64
 3   date              120 non-null    datetime64[us]
 4   event             120 non-null    str
 5   _source           120 non-null    str
 6   team1_id          120 non-null    int64
 7   team1_name        120 non-null    str
 8   team1_score       120 non-null    int64
 9   team1_rank        120 non-null    int64
 10  team2_id          120 non-null    int64
 11  team2_name        120 non-null    str
 12  team2_score       120 non-null    int64
 13  team2_rank        120 non-null    int64
 14  winner_id         120 non-null    int64
 15  winner_name       120 non-null    str
 16  team1_result      120 non-null    str
 17  team2_result      120 non-null    str
 18  score_difference  120 non-null    int64
dtypes: datetime64[us](1), int64(10), object(1), str(7)
memory usage: 24.1+ KB

# Verificando o DataFrame de mapas

In [154]:
maps_df.head()
maps_df.shape
maps_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 290 entries, 0 to 289
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   match_id          290 non-null    int64
 1   map_id            290 non-null    int64
 2   map_name          290 non-null    str
 3   team1_map_score   290 non-null    int64
 4   team2_map_score   290 non-null    int64
 5   round_difference  290 non-null    int64
dtypes: int64(5), str(1)
memory usage: 15.4 KB

# Removendo a coluna maps do DataFrame de partidas

In [155]:
matches_df = matches_df.drop( columns=["maps"] )

# Criando a pasta de saída

In [156]:
PROCESSED_DIR.mkdir( parents=True, exist_ok=True )

# Confirmação final

In [157]:
print(f"matches.csv: {len(matches_df)} partidas")
print(f"maps.csv: {len(maps_df)} mapas")

matches.csv: 120 partidas
maps.csv: 290 mapas

In [158]:
matches_df["best_of"].value_counts().sort_index()

best_of
1      8
3    106
5      6
Name: count, dtype: int64

In [159]:
maps_count = (
    maps_df
    .groupby("match_id")
    .size()
    .rename("maps_count")
    .reset_index()
)

In [160]:
validation_df = matches_df[
    ["match_id", "best_of"]
].merge(
    maps_count,
    on="match_id",
    how="left"
)

In [161]:
pd.crosstab(
    validation_df["best_of"],
    validation_df["maps_count"]
)

maps_count  1   2   3  4
best_of
1           8   0   0  0
3           0  58  48  0
5           0   0   2  4

# Salvando os dados tratados

In [162]:
matches_df.to_csv(
    PROCESSED_DIR / "matches.csv",
    index=False
)

maps_df.to_csv(
    PROCESSED_DIR / "maps.csv",
    index=False
)