In [1]:
import pandas as pd

In [107]:
matches_df = pd.read_csv(
    "../collector/processed/matches.csv"
)

maps_df = pd.read_csv(
    "../collector/processed/maps.csv"
)

# Procurando valores estranhos

In [108]:
matches_df[
    ["team1_score", "team2_score"]
].describe()

       team1_score  team2_score
count   120.000000   120.000000
mean      2.400000     1.408333
std       2.838511     2.273323
min       0.000000     0.000000
25%       1.750000     0.000000
50%       2.000000     1.000000
75%       2.000000     2.000000
max      13.000000    13.000000

In [109]:
maps_df[
    ["team1_map_score", "team2_map_score"]
].describe()

       team1_map_score  team2_map_score
count       290.000000       290.000000
mean         11.900000         9.793103
std           3.317199         4.045411
min           1.000000         0.000000
25%          11.000000         7.000000
50%          13.000000        11.000000
75%          13.000000        13.000000
max          25.000000        22.000000

# Verificar best_of

In [110]:
matches_df["best_of"].value_counts()

best_of
3    106
1      8
5      6
Name: count, dtype: int64

# Verificar mapas existentes

In [111]:
maps_df["map_name"].value_counts()

map_name
Dust2       75
Mirage      54
Nuke        45
Ancient     41
Inferno     25
Anubis      22
Overpass    18
Cache       10
Name: count, dtype: int64

# Partidas por time

In [112]:
teams = pd.concat([
    matches_df["team1_name"],
    matches_df["team2_name"]
])

teams.value_counts().head(6)

FUT         26
FURIA       26
Falcons     24
Vitality    24
MOUZ        21
Spirit      20
Name: count, dtype: int64

# Visão geral dos filtros de dados inconsistentes

In [113]:
print(f"Partidas: {len(matches_df)}")
print(f"Partidas únicas: {matches_df['match_id'].nunique()}")

print(f"\nMapas: {len(maps_df)}")

print(
    f"\nNaN em matches: "
    f"{matches_df.isna().sum().sum()}"
)

print(
    f"NaN em maps: "
    f"{maps_df.isna().sum().sum()}"
)

print(
    f"\nIDs de partidas duplicados: "
    f"{matches_df['match_id'].duplicated().sum()}"
)

Partidas: 120
Partidas únicas: 120

Mapas: 290

NaN em matches: 0
NaN em maps: 0

IDs de partidas duplicados: 0

# Testes Gerais

In [115]:
print("Matches:", matches_df.shape)
print("Maps:", maps_df.shape)

Matches: (120, 18)
Maps: (290, 6)

In [117]:
matches_df["best_of"].value_counts().sort_index()

best_of
1      8
3    106
5      6
Name: count, dtype: int64

In [118]:
maps_count = (
    maps_df
    .groupby("match_id")
    .size()
    .rename("maps_count")
    .reset_index()
)

In [119]:
validation_df = matches_df[
    ["match_id", "best_of"]
].merge(
    maps_count,
    on="match_id",
    how="left"
)

In [120]:
pd.crosstab(
    validation_df["best_of"],
    validation_df["maps_count"]
)

maps_count  1   2   3  4
best_of
1           8   0   0  0
3           0  58  48  0
5           0   0   2  4

In [121]:
validation_df[
    validation_df["maps_count"].isna()
]

Empty DataFrame
Columns: [match_id, best_of, maps_count]
Index: []

In [125]:
maps_df[
    ["team1_map_score", "team2_map_score"]
].describe()

       team1_map_score  team2_map_score
count       290.000000       290.000000
mean         11.900000         9.793103
std           3.317199         4.045411
min           1.000000         0.000000
25%          11.000000         7.000000
50%          13.000000        11.000000
75%          13.000000        13.000000
max          25.000000        22.000000